language: java
jdk:
  - openjdk8
dist: bionic
arch:
  - ppc64le
addons:
  apt:
    packages:
      - openjdk-8-jdk
      - ant-optional

  - ant download
      
script:
  - ant
  - ant download
  - ant test 
  
