language: java
dist: bionic
arch:
  - ppc64le
addons:
  apt:
    packages:
      - ant
      - git
      - junit
before_install:
- sudo apt-get -qq update
# ant-optional is needed for ant junit
- sudo apt-get install ant-optional

script:
  - git clone https://github.com/apache/tomcat-native.git
  - cd tomcat-native
  - git checkout 1.2.30
  - ant
  - ant test
  
