language: java
jdk:
  - openjdk8
dist: bionic
arch:
  - ppc64le
addons:
  apt:
    packages:
      - openjdk-8-jdk
      - ant 1.10.8
      - ant-optional


script:
  - ant
  - ant download
  - ant test 
  
