language: java
jdk:
  - openjdk8
dist: bionic
arch:
  - ppc64le
addons:
  apt:
    packages:
      - ant
      - ant-optional
      
before_install:
  - echo $(ant -version)
  - ant 1.10.9


script:
  - ant
  - ant download 
  
  
