language: java

dist: bionic
arch:
  - ppc64le
  
addons:
  apt:
    packages:
      - ant
      - ant-optional
script: 
  - ant 
  - sudo mkdir /usr/share/java/junit-4.11
  - ant download
  - ant test
  
  
  
