language: java
dist: bionic
arch:
  - ppc64le
addons:
  apt:
    packages:
      - ant
      - git
script:
  - git clone https://github.com/apache/tomcat-native.git
  - cd tomcat-native
  - git checkout 1.2.30
  - ant
  - ant test
  
