language: java
jdk:
  - openjdk8
dist: bionic
arch:
  - ppc64le
addons:
  apt:
    packages:
      - ant
      - ant-optional


script:
  - ant
  - ant download
  - sudo cp -a  /usr/share/java/.  ${ANT_HOME}/lib/
  - ant test 
  
