language: java

dist: bionic
arch:
  - ppc64le
  
addons:
  apt:
    packages:
      - ant
      - ant-optional
script: 
  - ant 
  - ant download
  - sudo cp -a  $HOME  ${ANT_HOME}/lib/
  - ant test
  
  
  
